// Copyright 2015 The Vanadium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file was auto-generated by the vanadium vdl tool.
// Package: security

package security

import (
	"v.io/v23/security"
	"v.io/v23/uniqueid"
	"v.io/v23/vdl"
)

func __VDLEnsureNativeBuilt() {
}

// TestCaveat is a caveat that's used in various security tests.
var TestCaveat = security.CaveatDescriptor{
	Id: uniqueid.Id{
		184,
		233,
		38,
		142,
		141,
		25,
		29,
		70,
		27,
		237,
		78,
		199,
		224,
		157,
		128,
		0,
	},
	ParamType: vdl.TypeOf(""),
}
