// This file was auto-generated by the veyron vdl tool.
// Source: caveat.vdl

package security

import (
	"v.io/core/veyron2/security"

	// The non-user imports are prefixed with "__" to prevent collisions.
	__vdl "v.io/core/veyron2/vdl"
)

// jniCaveat is a Go wrapper for a Java caveat.
type jniCaveat struct {
	Caveat security.Caveat
}

func (jniCaveat) __VDLReflect(struct {
	Name string "v.io/jni/veyron2/security.jniCaveat"
}) {
}

func init() {
	__vdl.Register(jniCaveat{})
}
