// This file was auto-generated by the veyron vdl tool.
// Source: caveat.vdl

package security

import (
	// VDL system imports
	"v.io/core/veyron2/vdl"

	// VDL user imports
	"v.io/core/veyron2/security"
)

// jniCaveat is a Go wrapper for a Java caveat.
type jniCaveat struct {
	Caveat security.Caveat
}

func (jniCaveat) __VDLReflect(struct {
	Name string "v.io/jni/veyron2/security.jniCaveat"
}) {
}

func init() {
	vdl.Register(jniCaveat{})
}
